openapi: "3.0.3"
info: 
  title: "Test Splunk Logging for Apigee"
  description: "This API is a no target API which has no backend services and is used for testing logging to Splpunk from within apigee"
  version: 1.0.0.0
  contact: 
    name: "EI SA/COE Team"
    email: "mayukh.chakravartti@adient.com"
paths:
  /testsplunklogging:
    get:
      description: "This is not targetting any backend server and is uesed only for tracking logging"
      responses:
        200:
          description: "Success Response"
      parameters: 
      - name: "trackingId"
        in: query
        description: "This is the process tracking id to be used in Boomi as well as Apigee"
        schema:
          type: string